import { useRouter } from 'next/router'
import { useContext, useState } from 'react'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import Head from 'next/head'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import Layout from '../components/Layout.js'
import UserContext from '../components/UserContext'
import { supabase } from './api/supabase.js'


export default function Contact() {
  const { user } = useContext(UserContext)
  const router = useRouter()
  const supabaseClient = useSupabaseClient()

  async function createUser(){
    const name = "Nicolas YORKE"
    const email = "yorke.nicolas.ece@gmail.com"
    const password = "tennis0512"

    const { user, session, error } = await supabase.auth.signUp(
      {
        email: 'example@email.com',
        password: 'example-password',
      },
      {
        data: { 
          first_name: 'John', 
          age: 27,
        }
      }
    )
  }
  
  if(user) router.push('/profile')
  return (
    <Layout>
      <Head>
        <title>WebTech - user signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={createUser}> button </button>
      <Auth
      
        supabaseClient={supabaseClient}
        appearance={{ theme: ThemeSupa }}
        providers={['github']}
       />
    </Layout>
  )
}
