import { useRouter } from 'next/router'
import { useContext, useState } from 'react'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import Head from 'next/head'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import Layout from '../components/Layout.js'
import UserContext from '../components/UserContext'
import { supabase } from './api/supabase.js'


export default function Contact() {
  const { user } = useContext(UserContext)
  const router = useRouter()
  const supabaseClient = useSupabaseClient()
  
  if(user) router.push('/profile')
  return (
    <Layout>
      <Head>
        <title>WebTech - user signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="flex flex-col items-center justify-center flex-grow min-h-screen px-0 py-16 bg-slate-300 ">
      <h1 className='wt-title '>
        Sign in/log in
      </h1>
      <div className="w-4/5 text-center bg-white border rounded-lg shadow-md sm:p-8 dark:bg-gray-800 dark:border-gray-700">
      
      <Auth
      
        supabaseClient={supabaseClient}
        appearance={{ theme: ThemeSupa }}
        providers={['github']}
       />
       </div>
       </main>
    </Layout>
  )
}
